# Generated by Django 4.1.5 on 2023-01-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='show_writer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Mode landscape saja; Lebar horizontal antara 1000px dan 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Teks untuk mendeskripsikan halaman ini.'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal dan waktu artikel diterbitkan.'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Mode landscape saja; Lebar horizontal antara 1000px dan 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Teks untuk mendeskripsikan halaman ini.'),
        ),
    ]
