# Generated by Django 4.1.5 on 2023-01-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0013_newscarouselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscarouselimages',
            name='carousel_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gambar Carousel'),
        ),
    ]
