# Generated by Django 4.1.5 on 2023-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_gallerypage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Teks untuk mendeskripsikan halaman ini.'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Teks untuk mendeskripsikan halaman ini.'),
        ),
    ]
