# Generated by Django 4.1.5 on 2023-01-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0003_homepage_person_homepage_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Bagian tambahan'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_title',
            field=models.CharField(blank=True, help_text='Judul untuk ditampilkan pada bagian tambahan', max_length=255),
        ),
    ]
